### PR TITLE
Google Cloud Deployment 

### PR DESCRIPTION
**Pull request by rdgh0st**
app.yaml created

### CODE REVIEW

**Review by jennatark — APPROVED** [review]

**Review by jennatark — APPROVED** [review]
swag money

**Review by rdgh0st — COMMENTED** [review]
test

**Review by rdgh0st — COMMENTED** [review]
test 2

**Review by Pwojcik2 — APPROVED** [review]

**Review by Undershot123 — COMMENTED** [review]
Looks good

**Pull request merged**
